---
# tasks file for palb
- name: create load balancer
  azure_rm_loadbalancer:
    resource_group: "{{ resource_group }}"
    name: "{{ lb_name }}"
    frontend_ip_configurations:
      - name: "{{ frontendip_name }}"
        public_ip_address: "{{ publicip_name }}"
    backend_address_pools:
      - name: "{{ backend_name }}"
    probes:
      - name: "{{ probe_name }}"
        port: 80
    load_balancing_rules:
      - name: "{{ lbrule_name }}"
        frontend_ip_configuration: "{{ frontendip_name }}" 
        backend_address_pool: "{{ backend_name }}"
        frontend_port: 80
        backend_port: 80
        probe: "{{ probe_name }}"
