---
#Start Creating the Public Ip for LB
- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    sku: standard
    name: "{{ public_ip_name }}"
    #- name: Create public IP address
    #  azure_rm_publicipaddress:
    #    resource_group: "{{ resource_group }}"
    #    allocation_method: Static
    #    sku: standard
    #    name: "{{ publicip_name1 }}"

