---
# tasks file for subnet
- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ subnet_name }}"
    address_prefix: "{{ address_prefix1 }}"
    virtual_network: "{{ vnet_name }}"
    #- name: Add subnet
    #azure_rm_subnet:
    #resource_group: "{{ resource_group }}"
    #name: "{{ subnet_name1 }}"
    #address_prefix: "{{ address_prefix1 }}"
    #virtual_network: "{{ virtual_network }}"
    #- name: Add subnet
    #  azure_rm_subnet:
    #resource_group: "{{ resource_group }}"
    #  name: "{{ subnet_name2 }}"
    #address_prefix: "{{ address_prefix2 }}"
    #    virtual_network: "{{ virtual_network }}"

