- hosts: localhost
  tasks:
          # - include_role:
          # name: rg
          #- include_role:
          # name: vnet
          # - include_role:
          # name: subnet
      - include_role:
           name: pslb
