---
# tasks file for Mgmt
- name: Add subnet for Firewall
  azure_rm_subnet:
    resource_group: "{{ resource_group }}-rg"
    name: "{{ subnet }}"
    address_prefix: "{{ Mgmt }}"
    virtual_network: "{{ resource_group }}-vnet"
- name: Add subnet fro Firewall01
  azure_rm_subnet:
    resource_group: "{{ resource_group1 }}-rg"
    name: "{{ subnet }}"
    address_prefix: "{{ Mgmt1 }}"
    virtual_network: "{{ resource_group1 }}-vnet"
