- hosts: localhost
  vars:
    resource_group: panfw
    address_prefixes: 10.1.0.0/16
    Mgmt: 10.1.0.0/24
    Internet: 10.1.1.0/24
    Intranet: 10.1.2.0/24
    mgmt_pvtip: 10.1.0.4
    internet_pvtip: 10.1.1.4
    intranet_pvtip: 10.1.2.4
  tasks:
      - include_role:
           name: panfw
      - include_role:
           name: Mgmt
      - include_role:
           name: Internet
      - include_role:
           name: Intranet
      - include_role:
           name: palfwvm
