---
# tasks file for ni
- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ nic_name }}"
    virtual_network: "{{ vnet_name }}"
    subnet: "{{ subnet_name }}"
    public_ip_name: "{{ publicip_name }}"
    security_group: "{{ nsg_name }}"
