---
# tasks file for ni
- name: Create a network with mutilple ip configurations
  azure_rm_networkinterface:
    name: "{{ nic_name }}"
    resource_group: "{{ resource_group }}"
    subnet_name: "{{ subnet_name }}"
    virtual_network_name: "{{ vnet_name }}"
    security_group_name: "{{ nsg_name }}"
    ip_configurations:
      - name: ipconfig1
        #        public_ip_address_name: "{{ publicip_name }}"
        primary: True
        private_ip_allocation_method: Static
        private_ip_address: 10.2.0.4 
- name: Create a network with mutilple ip configurations
  azure_rm_networkinterface:
    name: "{{ nic_name1 }}"
    resource_group: "{{ resource_group }}"
    subnet_name: "{{ subnet_name1 }}"
    virtual_network_name: "{{ vnet_name }}"
    security_group_name: "{{ nsg_name }}"
    ip_configurations:
      - name: ipconfig1
        # public_ip_address_name: "{{ publicip_name1 }}"
        primary: True
        private_ip_allocation_method: Static
        private_ip_address: 10.2.0.5
        #- name: Create a network interface with private IP address only (no Public IP)
        #  azure_rm_networkinterface:
        #    name: "{{ nic_name2 }}"
        #    resource_group: "{{ resource_group }}"
        #    virtual_network_name: "{{ vnet_name }}"
        #    subnet_name: "{{ subnet_name2 }}"
        #    security_group_name: "{{ nsg_name }}"
        #    ip_configurations:
        #      - name: ipconfig1
        #        private_ip_address: 10.1.2.4
        #        private_ip_allocation_method: Static
        #        primary: True
