---
# vars file for web-pydjango
resource_group: testrg
location: eastus
vnet_name: testvnet
address_prefixes: 20.0.0.0/16
subnet_name: testsubnet
address_prefix: 20.0.1.0/24
publicip_name: testpubip
nsg_name: testnsg
nic_name: testnic
vm_name: testvm
admin_username: azurekottur
ssh_key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0QdzuAeq5lSS5GvMommPcUp4WmnJ96XL93SkXrgUKi+EzRmAREq1q3ZAVK3vyGda5lsUki4icms/8n3bhEPX6OWSBLuXwkeGaQ6lvOIzcKTd0fySOapXwws/5YnliJjIZuNkJun1joVWjO1XlKdZpNsYm0peuYmu8sJakDE7Kclo7JGmolCg4L3GA4frXQv2rkNr9nugLp6eULL78BE7XNn/5OF+G4T88keHKJEZpHLQouwJDKnj48KJQAorgt7Ol9SUNWOB+Uq3A8HO4SqiXvF8PXuTd8LkSzXQ1u6PWfERwYAW3DYmXPQmiwsedyGWZMRd+euhX4WOA+z549zcJ
image_name: Ubuntudjangoimage
