---
# tasks file for web-nginx
- include_tasks: rg.yml
- include_tasks: vnet.yml
- include_tasks: subnet.yml
- include_tasks: paip.yml
- include_tasks: nsg.yml
- include_tasks: nic.yml
- include_tasks: aset.yml
- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    vm_size: Standard_B1s
    availability_set: "{{ as_name }}"
    admin_username: "{{ admin_name }}" 
    ssh_password_enabled: false
    ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key }}" 
    network_interfaces: "{{ nic_name }}"
    image: UbuntuapacheImage
- include_tasks: webserver02.yml
