---
# tasks file for Internet
- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}-rg"
    name: "{{ subnet }}"
    address_prefix: "{{ Internet }}"
    virtual_network: "{{ resource_group }}-vnet"
