---
# tasks file for ubuntuvm
- name: Create Firewall VM
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ vm_name }}"
    vm_size: Standard_D3_v2
    admin_username: "{{ admin_username }}"
    admin_password: azureuser@123456
    network_interfaces: "{{ nic_name , nic_name1 , nic_name2 }}"
    plan: 
      name: bundle2
      product: vmseries1
      publisher: paloaltonetworks
    image:
      offer: vmseries1
      publisher: paloaltonetworks
      sku: 'bundle2'
      version: latest
