---
# tasks file for pslb
- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    sku: Standard
    name: "{{ frontendip_name }}"  
- name: create load balancer
  azure_rm_loadbalancer:
        resource_group: "{{ resource_group }}"
        name: "{{ lb_name }}"
        frontend_ip_configurations:
          - name: "{{ frontendip_name }}"
            subnet: /subscriptions/68f6b170-cb61-4311-85a1-4f92bfaa44ec/resourceGroups/testrg/providers/Microsoft.Network/virtualNetworks/testvnet/subnets/testsubnet 
            private_ip_address: 20.0.1.10
            private_ip_allocation_method: dynamic
        backend_address_pools:
          - name: "{{ backend_name }}"
        probes:
          - name: "{{ probe_name }}"
            port: 80
        load_balancing_rules:
          - name: "{{ lbrule_name }}"
            frontend_ip_configuration: "{{ frontendip_name }}"
            backend_address_pool: "{{ backend_name }}"
            frontend_port: 80
            backend_port: 80
            probe: "{{ probe_name }}"
